name: Llvm-v2
on:
  push:
    branches:
    - main
jobs:
  build-wii:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh <17.x>
        cd . && mkdir build && cd build
        cmake -S .. -G "Ninja"
        ninja bin/llvm-cbe
        cd test/selectionsort
        clang-17 -S -emit-llvm -g main.c
        ../../build/tools/llvm-cbe/llvm-cbe main.ll
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: llvm-v2
        path: |
          ./
