name: Llvmbuild-v3
on:
  push:
    branches:
    - master
jobs:
  build-wii:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        git clone https://github.com/llvm/llvm-project.git
        cd llvm-project
        cmake -S llvm -B build -G Ninja
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: llvm-v3
        path: |
          ./
