name: Llvmbuild-v3
on:
  push:
    branches:
    - master
jobs:
  build-wii:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        git clone https://github.com/llvm/llvm-project.git
        cd llvm-project
        git checkout release/17.x
        mkdir llvm/build
        cd llvm/build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang"
        make
        mkdir llvm-project/llvm/projects
        cd llvm-project/llvm/projects
        git clone https://github.com/JuliaHubOSS/llvm-cbe
        cd ../build
        cmake -S .. -G "Ninja"
        ninja bin/llvm-cbe
        cd test/selectionsort
        clang-17 -S -emit-llvm -g main.c
        ../../build/tools/llvm-cbe/llvm-cbe main.ll
        gcc -o main.cbe main.cbe.c
        ./main.cbe
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: llvm-v3
        path: |
          ./
